version: '2'
services:
  php:
    image: yosmy/php
    container_name: symsonte_framework_php
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ../../:/var/www/
    networks:
      - development
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: "idekey=PHPSTORM remote_host=172.17.0.1"
    working_dir: /var/www

networks:
  development:
    external: true